#!/usr/bin/env python3
"""Build a source-to-export mapping for DJI Studio panorama exports."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def expected_output_name(source_path: Path) -> str:
    return f"{source_path.stem}_official.mp4"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_dir", type=Path, help="Directory containing source OSV files")
    parser.add_argument("export_dir", type=Path, help="Directory containing exported MP4 files")
    parser.add_argument(
        "--pattern",
        default="*.OSV",
        help="Glob for source files inside source_dir",
    )
    parser.add_argument(
        "--report-json",
        type=Path,
        help="Optional JSON report generated by dji_studio_report_exports.py",
    )
    parser.add_argument(
        "--json-out",
        type=Path,
        default=Path("exports/dji_studio_live/source_export_mapping.json"),
    )
    parser.add_argument(
        "--csv-out",
        type=Path,
        default=Path("exports/dji_studio_live/source_export_mapping.csv"),
    )
    args = parser.parse_args()

    source_dir = args.source_dir.expanduser().resolve()
    export_dir = args.export_dir.expanduser().resolve()
    sources = sorted(source_dir.glob(args.pattern))

    report_lookup: dict[str, dict[str, object]] = {}
    if args.report_json:
        report_data = json.loads(args.report_json.expanduser().resolve().read_text(encoding="utf-8"))
        for row in report_data.get("files", []):
            report_lookup[row["filename"]] = row

    rows: list[dict[str, object]] = []
    for source in sources:
        output_name = expected_output_name(source)
        output_path = export_dir / output_name
        report_row = report_lookup.get(output_name, {})
        rows.append(
            {
                "source_filename": source.name,
                "source_path": str(source),
                "output_filename": output_name,
                "output_path": str(output_path),
                "status": "ok" if output_path.exists() else "missing",
                "codec_name": report_row.get("codec_name"),
                "profile": report_row.get("profile"),
                "pix_fmt": report_row.get("pix_fmt"),
                "width": report_row.get("width"),
                "height": report_row.get("height"),
                "r_frame_rate": report_row.get("r_frame_rate"),
                "duration": report_row.get("duration"),
                "size": report_row.get("size"),
            }
        )

    payload = {
        "source_dir": str(source_dir),
        "export_dir": str(export_dir),
        "count": len(rows),
        "rows": rows,
    }

    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.csv_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    fieldnames = [
        "source_filename",
        "source_path",
        "output_filename",
        "output_path",
        "status",
        "codec_name",
        "profile",
        "pix_fmt",
        "width",
        "height",
        "r_frame_rate",
        "duration",
        "size",
    ]
    with args.csv_out.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(args.json_out.resolve())
    print(args.csv_out.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
